(define-module (mychannel packages goldendict)
  :use-module ((guix licenses) #:prefix license:)
  :use-module (guix packages)
  :use-module (guix download)
  :use-module (guix git-download)
  :use-module (guix build-system cmake)
  :use-module (guix build-system gnu)
  :use-module (guix build-system meson)
  :use-module (gnu packages qt)
  :use-module (guix build-system trivial)
  :use-module (guix build-system python)
  :use-module (guix build-system qt)
  :use-module (guix gexp)
  :use-module (guix packages)
  :use-module (guix deprecation)
  :use-module (guix utils)
  :use-module (gnu packages)
  :use-module (gnu packages bash)
  :use-module (gnu packages base)
  :use-module (gnu packages bison)
  :use-module (gnu packages check)
  :use-module (gnu packages cmake)
  :use-module (gnu packages compression)
  :use-module (gnu packages cpp)
  :use-module (gnu packages cups)
  :use-module (gnu packages curl)
  :use-module (gnu packages databases)
  :use-module (gnu packages documentation)
  :use-module (gnu packages elf)
  :use-module (gnu packages enchant)
  :use-module (gnu packages fontutils)
  :use-module (gnu packages flex)
  :use-module (gnu packages freedesktop)
  :use-module (gnu packages gcc)
  :use-module (gnu packages gdb)
  :use-module (gnu packages ghostscript)
  :use-module (gnu packages gl)
  :use-module (gnu packages glib)
  :use-module (gnu packages gnome)
  :use-module (gnu packages gnupg)
  :use-module (gnu packages gperf)
  :use-module (gnu packages graphics)
  :use-module (gnu packages gstreamer)
  :use-module (gnu packages gtk)
  :use-module (gnu packages icu4c)
  :use-module (gnu packages image)
  :use-module (gnu packages kde-frameworks)
  :use-module (gnu packages libevent)
  :use-module (gnu packages linux)
  :use-module (gnu packages llvm)
  :use-module (gnu packages maths)
  :use-module (gnu packages markup)
  :use-module (gnu packages networking)
  :use-module (gnu packages ninja)
  :use-module (gnu packages node)
  :use-module (gnu packages nss)
  :use-module (gnu packages pciutils)
  :use-module (gnu packages pcre)
  :use-module (gnu packages perl)
  :use-module (gnu packages pkg-config)
  :use-module (gnu packages pulseaudio)
  :use-module (gnu packages protobuf)
  :use-module (gnu packages python)
  :use-module (gnu packages python-build)
  :use-module (gnu packages python-xyz)
  :use-module (gnu packages python-web)
  :use-module (gnu packages regex)
  :use-module (gnu packages ruby)
  :use-module (gnu packages sdl)
  :use-module (gnu packages serialization)
  :use-module (gnu packages sqlite)
  :use-module (gnu packages telephony)
  :use-module (gnu packages tls)
  :use-module (gnu packages valgrind)
  :use-module (gnu packages video)
  :use-module (gnu packages vulkan)
  :use-module (gnu packages xdisorg)
  :use-module (gnu packages xiph)
  :use-module (gnu packages xorg)
  :use-module (gnu packages xml)
  :use-module (gnu packages compression)
  :use-module (gnu packages hunspell)
  :use-module (gnu packages education)
  :use-module (gnu packages qt)
  :use-module (gnu packages version-control)
  :use-module (gnu packages textutils)
  :use-module (mychannel packages qtwebkit)
  :use-module (srfi srfi-1)
  )

(define-public
  (package
    (name "goldendict")
    (version "1.5.0")
    (source
     (origin
       (method url-fetch)
       (uri (string-append "https://github.com/goldendict/goldendict/archive/refs/tags/" version  ".tar.gz"))
       (sha256
        (base32
         "0z1c86pcw52crmy1kiwp1kkv8a324handxf5zlkc0k77xilf1y7r"))))
    (build-system gnu-build-system)
    (native-inputs (list git pkg-config))
    (inputs
     (list bzip2 ffmpeg gcc glibc hunspell ao libeb libtiff libvorbis libx11 libxtst lzo opencc qtbase-5 qtmultimedia-5 qtsvg-5 qttools-5 qtwebkit qtx11extras xz zlib `(,zstd "lib")))

    (arguments
     `(#:phases
       (modify-phases %standard-phases
         (replace 'configure
           (lambda* (#:key outputs inputs #:allow-other-keys)
             (invoke "qmake"
                     (string-append "QMAKE_LRELEASE=" (which "lrelease"))
                     (string-append "PREFIX=" (assoc-ref outputs "out"))
                     "CONFIG+=chinese_conversion_support"
                     "CONFIG+=zim_support"
                     "goldendict.pro")))
         )))
    (home-page "http://goldendict.org/")
    (synopsis "Feature-rich dictionary lookup program")
    (description "GoldenDict is a feature-rich dictionary lookup program, supporting multiple dictionary formats (StarDict/Babylon/Lingvo/Dictd/AARD/MDict/SDict) and online dictionaries, featuring perfect article rendering with the complete markup, illustrations and other content retained, and allowing you to type in words without any accents or correct case.")
    (license license:gpl3+)))
